# Application Configuration File

# Server Configuration
server:
  # Server Port
  port: 8181

# Spring Application Configuration
spring:
  # Application Profile
  application:
    # Application Name
    name: SpringBootFileAndProcess

# Application Security Configuration
app:
  security:
    # Username for API authentication
    username: ${SECURITY_USERNAME:admin}
    # Password for API authentication
    password: ${SECURITY_PASSWORD:admin}

# Logging Configuration
logging:
  level:
    root: INFO
    fr.tiogars.springbootfileandprocess: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/springbootfileandprocess.log
